export const foodCategories = [
  { id: 1, name: "North Indian", image: "🍛" },
  { id: 2, name: "Biryani", image: "🍚" },
  { id: 3, name: "Chinese", image: "🥢" },
  { id: 4, name: "Desserts", image: "🍰" },
  { id: 5, name: "Cake", image: "🎂" },
  { id: 6, name: "Pizza", image: "🍕" },
  { id: 7, name: "Rolls", image: "🌯" },
  { id: 8, name: "South Indian", image: "🥘" },
  { id: 9, name: "Noodles", image: "🍜" },
  { id: 10, name: "Burger", image: "🍔" },
  { id: 11, name: "Ice Cream", image: "🍦" },
  { id: 12, name: "Momo", image: "🥟" },
  { id: 13, name: "Pasta", image: "🍝" },
  { id: 14, name: "Paratha", image: "🥙" },
  { id: 15, name: "Dosa", image: "🥘" },
  { id: 16, name: "Salad", image: "🥗" },
  { id: 17, name: "Pastry", image: "🥐" },
  { id: 18, name: "Rasgulla", image: "🍮" },
  { id: 19, name: "Shawarma", image: "🌮" },
  { id: 20, name: "Khichdi", image: "🍲" },
];