export const restaurants = [
  {
    id: 1,
    name: "Biryani House",
    description:
      "Authentic dum-style biryanis cooked with rich spices. A perfect blend of aroma and tradition in every bite.",
    categories: [2],
    image: "/biryani.jpg",
    type: "non-veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Hyderabadi Biryani", price: 250 },
      { id: 2, name: "Lucknowi Biryani", price: 280 },
      { id: 3, name: "Kolkata Biryani", price: 240 },
      { id: 4, name: "Biryani with Raita", price: 300 },
    ],
  },
  {
    id: 2,
    name: "South Spice",
    description:
      "Fresh South Indian dishes made with traditional recipes. Crispy dosas and flavorful sambars served hot.",
    categories: [8, 15],
    image: "/south.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Dosa", price: 120 },
      { id: 2, name: "Uttapam", price: 130 },
      { id: 3, name: "Sambar Rice", price: 100 },
      { id: 4, name: "Coconut Chutney", price: 30 },
    ],
  },
  {
    id: 3,
    name: "Sweet World",
    description:
      "Traditional Indian sweets crafted with premium ingredients. A paradise for every dessert lover.",
    categories: [4, 18],
    image: "/dessert.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Gulab Jamun", price: 80 },
      { id: 2, name: "Rasgulla", price: 90 },
      { id: 3, name: "Jalebi", price: 70 },
      { id: 4, name: "Kheer", price: 100 },
    ],
  },
  {
    id: 4,
    name: "Tandoori King",
    description:
      "Flame-grilled tandoori delights with smoky flavors. Juicy, spicy, and cooked to perfection.",
    categories: [1],
    image: "/tandoori.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Tandoori Chicken", price: 350 },
      { id: 2, name: "Tandoori Paneer", price: 300 },
      { id: 3, name: "Tandoori Fish", price: 400 },
      { id: 4, name: "Tandoori Naan", price: 50 },
    ],
  },
  {
    id: 5,
    name: "Curry Master",
    description:
      "Rich and creamy curries made from authentic spices. A comforting North Indian experience.",
    categories: [1],
    image: "/curry.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Butter Chicken Curry", price: 320 },
      { id: 2, name: "Paneer Tikka Masala", price: 280 },
      { id: 3, name: "Chole Masala", price: 180 },
      { id: 4, name: "Rice Bowl", price: 80 },
    ],
  },

  {
    id: 6,
    name: "Chai Corner",
    description:
      "Freshly brewed teas paired with tasty snacks. The perfect evening hangout spot.",
    categories: [14],
    image: "/chai.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Masala Chai", price: 30 },
      { id: 2, name: "Ginger Chai", price: 35 },
      { id: 3, name: "Adrak Chai", price: 40 },
      { id: 4, name: "Chai Biscuits Pack", price: 50 },
    ],
  },

  {
    id: 7,
    name: "Bengal Kitchen",
    description:
      "Authentic Bengali cuisine with traditional flavors. Sweet and savory delights from the East.",
    categories: [1],
    image: "/bengal.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Luchi Alur Tarkari", price: 150 },
      { id: 2, name: "Machher Jhol", price: 280 },
      { id: 3, name: "Mishti Doi", price: 70 },
      { id: 4, name: "Sandesh", price: 60 },
    ],
  },

  {
    id: 8,
    name: "Southeast Flavors",
    description:
      "A blend of Thai and Vietnamese specialties. Fresh herbs and bold Asian spices.",
    categories: [3, 9],
    image: "/seasia.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Pad Thai", price: 220 },
      { id: 2, name: "Vietnam Pho", price: 240 },
      { id: 3, name: "Tom Yum Soup", price: 200 },
      { id: 4, name: "Spring Rolls", price: 150 },
    ],
  },

  {
    id: 9,
    name: "Tokyo Express",
    description:
      "Quick Japanese favorites served fresh daily. Sushi, ramen, and more in every order.",
    categories: [3, 9],
    image: "/tokyo.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Sushi Roll", price: 350 },
      { id: 2, name: "Ramen Noodles", price: 280 },
      { id: 3, name: "Tempura Plate", price: 320 },
      { id: 4, name: "Gyoza", price: 180 },
    ],
  },

  {
    id: 10,
    name: "Shanghai Wok",
    description:
      "Wok-tossed Chinese dishes bursting with flavor. Street-style classics done right.",
    categories: [3, 9],
    image: "/shanghai.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Fried Rice", price: 180 },
      { id: 2, name: "Chow Mein", price: 200 },
      { id: 3, name: "Manchurian Balls", price: 220 },
      { id: 4, name: "Kung Pao Chicken", price: 250 },
    ],
  },
  {
    id: 11,
    name: "European Bistro",
    description:
      "Elegant European classics made with authentic recipes. A cozy spot for rich continental flavors.",
    categories: [13],
    image: "/european.jpg",
    type: "both",
    rating: 4.6,
    menu: [
      { id: 1, name: "Pasta Carbonara", price: 320 },
      { id: 2, name: "Grilled Steak", price: 450 },
      { id: 3, name: "Caesar Salad", price: 200 },
      { id: 4, name: "Bruschetta", price: 150 },
    ],
  },
  {
    id: 12,
    name: "Quick Bites",
    description:
      "Fast food favorites served hot and fresh. Perfect for quick cravings and tasty combos.",
    categories: [10, 6],
    image: "/fastfood.jpg",
    type: "both",
    rating: 4.0,
    menu: [
      { id: 1, name: "Burger Combo", price: 180 },
      { id: 2, name: "Fried Chicken", price: 160 },
      { id: 3, name: "Pizza Slice", price: 120 },
      { id: 4, name: "French Fries", price: 80 },
    ],
  },
  {
    id: 13,
    name: "Kebab Palace",
    description:
      "Juicy kebabs grilled over open flames. A paradise for lovers of smoky flavors.",
    categories: [1, 7],
    image: "/kebab.jpg",
    type: "non-veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Chicken Seekh Kebab", price: 280 },
      { id: 2, name: "Lamb Kebab", price: 350 },
      { id: 3, name: "Paneer Kebab", price: 240 },
      { id: 4, name: "Kebab Roll", price: 180 },
    ],
  },
  {
    id: 14,
    name: "Noodle Express",
    description:
      "Flavorful noodle bowls tossed in bold sauces. Comfort food ready in minutes.",
    categories: [9],
    image: "/noodle.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Hakka Noodles", price: 160 },
      { id: 2, name: "Schezwan Noodles", price: 180 },
      { id: 3, name: "Plain Noodles", price: 120 },
      { id: 4, name: "Mixed Veg Noodles", price: 140 },
    ],
  },
  {
    id: 15,
    name: "Pizza Hub",
    description:
      "Freshly baked pizzas loaded with cheese. Classic and creative toppings for every mood.",
    categories: [6],
    image: "/pizza.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Margherita Pizza", price: 280 },
      { id: 2, name: "Pepperoni Pizza", price: 320 },
      { id: 3, name: "Veggie Pizza", price: 250 },
      { id: 4, name: "Cheese Crust", price: 300 },
    ],
  },
  {
    id: 16,
    name: "Samosa Stall",
    description:
      "Crispy golden samosas filled with delicious stuffing. A true Indian snack favorite.",
    categories: [7],
    image: "/samosa.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Aloo Samosa", price: 40 },
      { id: 2, name: "Paneer Samosa", price: 60 },
      { id: 3, name: "Meat Samosa", price: 80 },
      { id: 4, name: "Samosa Combo", price: 120 },
    ],
  },
  {
    id: 17,
    name: "Modern Cafe",
    description:
      "Premium coffees brewed to perfection. A stylish space to relax and recharge.",
    categories: [16],
    image: "/cafe.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Espresso", price: 80 },
      { id: 2, name: "Cappuccino", price: 120 },
      { id: 3, name: "Latte", price: 130 },
      { id: 4, name: "Iced Coffee", price: 100 },
    ],
  },
  {
    id: 18,
    name: "Rajasthani Kitchen",
    description:
      "Authentic Rajasthani dishes made with traditional spices. Experience royal flavors in every bite.",
    categories: [1],
    image: "/rajasthan.jpg",
    type: "veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Dal Baati Churma", price: 200 },
      { id: 2, name: "Gatte Ki Sabzi", price: 180 },
      { id: 3, name: "Bajra Roti", price: 60 },
      { id: 4, name: "Ker Sangri", price: 140 },
    ],
  },
  {
    id: 19,
    name: "Momos House",
    description:
      "Steamed and fried momos packed with flavor. A go-to place for dumpling lovers.",
    categories: [12],
    image: "/momos.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Chicken Momos", price: 150 },
      { id: 2, name: "Veg Momos", price: 120 },
      { id: 3, name: "Paneer Momos", price: 140 },
      { id: 4, name: "Momo Soup", price: 180 },
    ],
  },
  {
    id: 20,
    name: "Health Bowl",
    description:
      "Nutritious bowls made with fresh ingredients. Healthy eating without compromising taste.",
    categories: [16],
    image: "/health.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Buddha Bowl", price: 280 },
      { id: 2, name: "Quinoa Salad", price: 250 },
      { id: 3, name: "Green Smoothie", price: 150 },
      { id: 4, name: "Protein Shake", price: 180 },
    ],
  },
  {
    id: 21,
    name: "Chole Bhature",
    description:
      "North Indian street-style comfort food. Fluffy bhature served with spicy chole.",
    categories: [1, 14],
    image: "/chole.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Chole Bhature", price: 150 },
      { id: 2, name: "Kulche with Chole", price: 140 },
      { id: 3, name: "Puri with Chole", price: 120 },
      { id: 4, name: "Bhature with Butter", price: 180 },
    ],
  },
  {
    id: 22,
    name: "Waffle Corner",
    description:
      "Crispy waffles topped with sweet delights. A treat for every dessert lover.",
    categories: [4, 5],
    image: "/waffle.jpg",
    type: "veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Chocolate Waffle", price: 200 },
      { id: 2, name: "Strawberry Waffle", price: 220 },
      { id: 3, name: "Nutella Waffle", price: 240 },
      { id: 4, name: "Plain Waffle", price: 150 },
    ],
  },
  {
    id: 23,
    name: "Grilled Paradise",
    description:
      "Perfectly grilled meats and vegetables. Smoky flavors cooked to perfection.",
    categories: [1],
    image: "/grilled.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Grilled Chicken Breast", price: 380 },
      { id: 2, name: "Grilled Fish Fillet", price: 420 },
      { id: 3, name: "Grilled Vegetables", price: 200 },
      { id: 4, name: "Grilled Paneer", price: 280 },
    ],
  },
  {
    id: 24,
    name: "Idli Sambar",
    description:
      "Soft idlis served with rich sambar and chutney. A South Indian breakfast classic.",
    categories: [8, 15],
    image: "/idli.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Idli with Sambar", price: 80 },
      { id: 2, name: "Idli with Chutney", price: 70 },
      { id: 3, name: "Gundam Idli", price: 90 },
      { id: 4, name: "Rice Idli", price: 100 },
    ],
  },
  {
    id: 25,
    name: "Fruit Shake Parlor",
    description:
      "Fresh fruit shakes blended daily. Cool, refreshing, and naturally sweet.",
    categories: [16],
    image: "/fruitshake.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Mango Shake", price: 120 },
      { id: 2, name: "Banana Shake", price: 100 },
      { id: 3, name: "Strawberry Shake", price: 130 },
      { id: 4, name: "Mixed Fruit Shake", price: 140 },
    ],
  },
  {
    id: 26,
    name: "Korean Grill",
    description:
      "Authentic Korean BBQ with bold spices. Sizzling plates full of flavor.",
    categories: [3],
    image: "/korean.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Bulgogi", price: 350 },
      { id: 2, name: "Bibimbap", price: 320 },
      { id: 3, name: "Korean Fried Chicken", price: 380 },
      { id: 4, name: "Kimchi Roll", price: 200 },
    ],
  },
  {
    id: 27,
    name: "Panipuri Point",
    description:
      "Crispy golgappas filled with tangy water. Street food bursting with flavor.",
    categories: [7],
    image: "/panipuri.jpg",
    type: "veg",
    rating: 4.0,
    menu: [
      { id: 1, name: "Panipuri", price: 50 },
      { id: 2, name: "Gol Gappa", price: 60 },
      { id: 3, name: "Bhel Puri", price: 80 },
      { id: 4, name: "Sev Puri", price: 70 },
    ],
  },
  {
    id: 28,
    name: "Thai Cuisine",
    description:
      "Traditional Thai curries and noodles. Aromatic herbs and bold flavors in every dish.",
    categories: [3, 9],
    image: "/thai.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Green Curry", price: 280 },
      { id: 2, name: "Pad See Ew", price: 260 },
      { id: 3, name: "Massaman Curry", price: 300 },
      { id: 4, name: "Basil Chicken", price: 290 },
    ],
  },
  {
    id: 29,
    name: "Lebanese House",
    description:
      "Authentic Middle Eastern wraps and platters. Fresh hummus and grilled specialties.",
    categories: [19, 7],
    image: "/lebanese.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Falafel Wrap", price: 180 },
      { id: 2, name: "Shawarma", price: 220 },
      { id: 3, name: "Hummus Plate", price: 150 },
      { id: 4, name: "Tabbouleh Salad", price: 160 },
    ],
  },
  {
    id: 30,
    name: "Dhaba Style",
    description:
      "Rustic Punjabi dhaba flavors. Hearty meals cooked with traditional spices.",
    categories: [1, 14],
    image: "/dhaba.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Sarson Ka Saag", price: 220 },
      { id: 2, name: "Makki Ki Roti", price: 50 },
      { id: 3, name: "Dal Makhani", price: 240 },
      { id: 4, name: "Paneer Butter Masala", price: 280 },
    ],
  },
  {
    id: 31,
    name: "Sandwich Hub",
    description:
      "Freshly prepared sandwiches with premium fillings. Quick bites perfect for any time of day.",
    categories: [7],
    image: "/sandwich.jpg",
    type: "both",
    rating: 4.1,
    menu: [
      { id: 1, name: "Veggie Sandwich", price: 120 },
      { id: 2, name: "Chicken Sandwich", price: 160 },
      { id: 3, name: "Paneer Sandwich", price: 140 },
      { id: 4, name: "Club Sandwich", price: 200 },
    ],
  },
  {
    id: 32,
    name: "Ice Cream Paradise",
    description:
      "Creamy scoops in classic and exotic flavors. A sweet escape for every dessert lover.",
    categories: [11, 4],
    image: "/icecream.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Vanilla Scoop", price: 100 },
      { id: 2, name: "Chocolate Scoop", price: 100 },
      { id: 3, name: "Strawberry Scoop", price: 100 },
      { id: 4, name: "Cookie Dough", price: 120 },
    ],
  },
  {
    id: 33,
    name: "Mexican Fiesta",
    description:
      "Spicy tacos and loaded burritos made fresh. Authentic Mexican street-style flavors.",
    categories: [7],
    image: "/mexican.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Tacos", price: 200 },
      { id: 2, name: "Burrito", price: 240 },
      { id: 3, name: "Enchiladas", price: 260 },
      { id: 4, name: "Guacamole Dip", price: 150 },
    ],
  },
  {
    id: 34,
    name: "Dosa King",
    description:
      "Crispy dosas served with rich sambar and chutney. South Indian flavors done right.",
    categories: [8, 15],
    image: "/dosakking.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Masala Dosa", price: 130 },
      { id: 2, name: "Paneerdosa", price: 150 },
      { id: 3, name: "Onion Dosa", price: 120 },
      { id: 4, name: "Ghee Roast Dosa", price: 140 },
    ],
  },
  {
    id: 35,
    name: "Pasta Paradise",
    description:
      "Italian pasta cooked in rich, flavorful sauces. Comfort food with a continental touch.",
    categories: [13],
    image: "/pasta.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Penne Arrabbiata", price: 280 },
      { id: 2, name: "Fettuccine Alfredo", price: 300 },
      { id: 3, name: "Spaghetti Bolognese", price: 290 },
      { id: 4, name: "Lasagna", price: 320 },
    ],
  },
  {
    id: 36,
    name: "Vada Pav Corner",
    description:
      "Mumbai’s iconic street snack served fresh. Spicy, crispy, and full of flavor.",
    categories: [7],
    image: "/vadapav.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Vada Pav", price: 50 },
      { id: 2, name: "Batata Vada", price: 60 },
      { id: 3, name: "Misal Pav", price: 80 },
      { id: 4, name: "Combo Pack", price: 130 },
    ],
  },
  {
    id: 37,
    name: "Juice Bar",
    description:
      "Freshly squeezed juices and smoothies. Healthy refreshment made delicious.",
    categories: [16],
    image: "/juicebar.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Orange Juice", price: 80 },
      { id: 2, name: "Apple Juice", price: 90 },
      { id: 3, name: "Carrot Juice", price: 70 },
      { id: 4, name: "Mixed Citrus", price: 100 },
    ],
  },
  {
    id: 38,
    name: "Afghan Breads",
    description:
      "Traditional Afghan specialties and breads. Rich spices and hearty flavors.",
    categories: [1],
    image: "/afghan.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Qabuli Pulao", price: 280 },
      { id: 2, name: "Chapli Kebab", price: 250 },
      { id: 3, name: "Naan", price: 60 },
      { id: 4, name: "Kofta", price: 220 },
    ],
  },
  {
    id: 39,
    name: "Biryani Express",
    description:
      "Fast and flavorful biryanis served hot. Classic recipes made quick and delicious.",
    categories: [2],
    image: "/biryaniexpress.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Chicken Biryani", price: 260 },
      { id: 2, name: "Mutton Biryani", price: 320 },
      { id: 3, name: "Veg Biryani", price: 200 },
      { id: 4, name: "Fish Biryani", price: 380 },
    ],
  },
  {
    id: 40,
    name: "Crepe Cafe",
    description:
      "Sweet and savory crepes made fresh. A delightful French-inspired experience.",
    categories: [4, 5],
    image: "/crepe.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Chocolate Crepe", price: 180 },
      { id: 2, name: "Strawberry Crepe", price: 200 },
      { id: 3, name: "Nutella Banana", price: 220 },
      { id: 4, name: "Vanilla Crepe", price: 160 },
    ],
  },
  {
    id: 41,
    name: "Grilled Cheese",
    description:
      "Golden toasted sandwiches with melted cheese. Simple comfort food made perfect.",
    categories: [7],
    image: "/grilledcheese.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Classic Grilled Cheese", price: 140 },
      { id: 2, name: "Bacon Grilled Cheese", price: 180 },
      { id: 3, name: "Tomato Grilled Cheese", price: 160 },
      { id: 4, name: "Veggie Grilled Cheese", price: 150 },
    ],
  },
  {
    id: 42,
    name: "Vietnamese Pho",
    description:
      "Authentic pho with rich aromatic broth. Fresh herbs and bold Vietnamese flavors.",
    categories: [3, 9],
    image: "/phocafe.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Beef Pho", price: 240 },
      { id: 2, name: "Chicken Pho", price: 220 },
      { id: 3, name: "Vegetable Pho", price: 180 },
      { id: 4, name: "Seafood Pho", price: 300 },
    ],
  },
  {
    id: 43,
    name: "Soya Chaap House",
    description:
      "Delicious vegetarian chaap in smoky flavors. Spicy, juicy, and satisfying.",
    categories: [1, 7],
    image: "/soyachaap.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Tandoori Soya Chaap", price: 220 },
      { id: 2, name: "Gravy Soya Chaap", price: 240 },
      { id: 3, name: "Smoked Soya Chaap", price: 260 },
      { id: 4, name: "Soya Chaap Roll", price: 180 },
    ],
  },
  {
    id: 44,
    name: "Donut Shop",
    description:
      "Freshly baked donuts topped with sweetness. Soft, fluffy, and irresistible.",
    categories: [4, 17],
    image: "/donut.jpg",
    type: "veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Glazed Donut", price: 80 },
      { id: 2, name: "Chocolate Donut", price: 100 },
      { id: 3, name: "Sprinkle Donut", price: 120 },
      { id: 4, name: "Donut Box", price: 300 },
    ],
  },
  {
    id: 45,
    name: "Meatball Joint",
    description:
      "Juicy meatballs cooked in rich sauces. A hearty treat for meat lovers.",
    categories: [1],
    image: "/meatball.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Swedish Meatballs", price: 280 },
      { id: 2, name: "Italian Meatballs", price: 290 },
      { id: 3, name: "Asian Meatballs", price: 260 },
      { id: 4, name: "Meatball Sandwich", price: 220 },
    ],
  },
  {
    id: 46,
    name: "Bhelpuri Stall",
    description:
      "Tangy and crunchy street-style chaat. A burst of flavors in every bite.",
    categories: [7],
    image: "/bhelpuri.jpg",
    type: "veg",
    rating: 4.0,
    menu: [
      { id: 1, name: "Bhel Puri", price: 80 },
      { id: 2, name: "Raj Kachori", price: 90 },
      { id: 3, name: "Chaat Papdi", price: 85 },
      { id: 4, name: "Mix Chaat", price: 120 },
    ],
  },
  {
    id: 47,
    name: "Bubble Tea House",
    description:
      "Trendy bubble teas in exciting flavors. Refreshing drinks with chewy boba pearls.",
    categories: [16],
    image: "/bubbletea.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Taro Bubble Tea", price: 150 },
      { id: 2, name: "Brown Sugar Boba", price: 160 },
      { id: 3, name: "Matcha Bubble Tea", price: 170 },
      { id: 4, name: "Strawberry Boba", price: 150 },
    ],
  },
  {
    id: 48,
    name: "Fish & Chips Shop",
    description:
      "Crispy battered fish served golden brown. A classic coastal comfort meal.",
    categories: [1],
    image: "/fishchips.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Battered Fish", price: 320 },
      { id: 2, name: "Crispy Fish", price: 300 },
      { id: 3, name: "Fish Fillet", price: 280 },
      { id: 4, name: "Fish & Chips Combo", price: 380 },
    ],
  },
  {
    id: 49,
    name: "Falafel Street",
    description:
      "Fresh falafel wraps and platters. Middle Eastern flavors made authentic.",
    categories: [7],
    image: "/falafel.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Falafel Plate", price: 160 },
      { id: 2, name: "Falafel Wrap", price: 180 },
      { id: 3, name: "Falafel Salad", price: 200 },
      { id: 4, name: "Spicy Falafel", price: 180 },
    ],
  },
  {
    id: 50,
    name: "Asian Fusion",
    description:
      "Creative dishes inspired by Asian cuisines. Bold flavors with a modern twist.",
    categories: [3, 9],
    image: "/fusion.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Fusion Bowl", price: 300 },
      { id: 2, name: "Asian Tacos", price: 280 },
      { id: 3, name: "Fusion Noodles", price: 260 },
      { id: 4, name: "Fusion Rice", price: 240 },
    ],
  },
  {
    id: 51,
    name: "Moti Mahal Delux",
    description:
      "Legendary North Indian cuisine with rich gravies. Royal flavors crafted with tradition.",
    categories: [1],
    image: "/motimahal.jpg",
    type: "both",
    rating: 4.7,
    menu: [
      { id: 1, name: "Butter Chicken", price: 420 },
      { id: 2, name: "Dal Makhani", price: 320 },
      { id: 3, name: "Tandoori Chicken", price: 380 },
      { id: 4, name: "Paneer Makhani", price: 350 },
    ],
  },
  {
    id: 52,
    name: "Daryaganj Originals",
    description:
      "Home of authentic butter chicken recipes. Classic North Indian flavors redefined.",
    categories: [1],
    image: "/daryaganj.jpg",
    type: "both",
    rating: 4.6,
    menu: [
      { id: 1, name: "Original Butter Chicken", price: 440 },
      { id: 2, name: "Handi Chicken", price: 400 },
      { id: 3, name: "Kadhai Paneer", price: 340 },
      { id: 4, name: "Garlic Naan", price: 90 },
    ],
  },
  {
    id: 53,
    name: "Punjab Grill House",
    description:
      "Bold Punjabi spices and hearty meals. Traditional dishes packed with flavor.",
    categories: [1],
    image: "/punjabgrill.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Amritsari Kulcha", price: 180 },
      { id: 2, name: "Paneer Tikka", price: 320 },
      { id: 3, name: "Kadhai Chicken", price: 390 },
      { id: 4, name: "Dal Tadka", price: 260 },
    ],
  },
  {
    id: 54,
    name: "Tandoori Nights",
    description:
      "Late-night tandoori cravings sorted. Smoky grilled delights served hot.",
    categories: [1, 7],
    image: "/tandoorinights.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Chicken Seekh Kebab", price: 360 },
      { id: 2, name: "Malai Tikka", price: 380 },
      { id: 3, name: "Tandoori Roti", price: 40 },
      { id: 4, name: "Paneer Tikka", price: 340 },
    ],
  },
  {
    id: 55,
    name: "Handi Junction",
    description:
      "Slow-cooked handi dishes full of rich flavor. Traditional cooking with authentic spices.",
    categories: [2],
    image: "/handi.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Handi Paneer", price: 330 },
      { id: 2, name: "Handi Chicken", price: 410 },
      { id: 3, name: "Butter Naan", price: 70 },
      { id: 4, name: "Jeera Rice", price: 180 },
    ],
  },
  {
    id: 56,
    name: "Kebab & Curries",
    description:
      "Flavorful kebabs paired with rich curries. A true North Indian feast.",
    categories: [1, 7],
    image: "/kebabcurry.jpg",
    type: "non-veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Mutton Seekh Kebab", price: 420 },
      { id: 2, name: "Chicken Tikka", price: 360 },
      { id: 3, name: "Mutton Rogan Josh", price: 480 },
      { id: 4, name: "Rumali Roti", price: 50 },
    ],
  },
  {
    id: 57,
    name: "Delhi Darbar",
    description:
      "Classic Mughlai dishes inspired by Delhi flavors. Rich gravies and comforting meals.",
    categories: [1],
    image: "/delhidarbar.jpg",
    type: "both",
    rating: 4.6,
    menu: [
      { id: 1, name: "Paneer Butter Masala", price: 350 },
      { id: 2, name: "Dal Makhani", price: 310 },
      { id: 3, name: "Kadhai Chicken", price: 400 },
      { id: 4, name: "Laccha Paratha", price: 80 },
    ],
  },
  {
    id: 58,
    name: "Royal Tandoor",
    description:
      "Premium tandoori platters and creamy curries. Royal taste in every serving.",
    categories: [1, 7],
    image: "/royaltandoor.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Tandoori Platter", price: 520 },
      { id: 2, name: "Chicken Afghani", price: 420 },
      { id: 3, name: "Paneer Lababdar", price: 360 },
      { id: 4, name: "Butter Roti", price: 45 },
    ],
  },
  {
    id: 59,
    name: "Makhani Magic",
    description:
      "Specialists in creamy makhani gravies. Smooth, rich, and indulgent flavors.",
    categories: [1],
    image: "/makhani.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Butter Chicken", price: 410 },
      { id: 2, name: "Paneer Makhani", price: 340 },
      { id: 3, name: "Dal Makhani", price: 300 },
      { id: 4, name: "Kadhai Paneer", price: 330 },
    ],
  },
  {
    id: 60,
    name: "Punjab Da Dhaba",
    description:
      "Authentic roadside Punjabi flavors. Rustic comfort food made with love.",
    categories: [1],
    image: "/punjabdhaba.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Sarson Ka Saag", price: 260 },
      { id: 2, name: "Makki Ki Roti", price: 60 },
      { id: 3, name: "Handi Chicken", price: 390 },
      { id: 4, name: "Paneer Tikka Masala", price: 350 },
    ],
  },
];
