export const restaurants = [
  {
    id: 1,
    name: "Biryani House",
    categories: [2],
    image: "/biryani.jpg",
    type: "non-veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Hyderabadi Biryani", price: 250 },
      { id: 2, name: "Lucknowi Biryani", price: 280 },
      { id: 3, name: "Kolkata Biryani", price: 240 },
      { id: 4, name: "Biryani with Raita", price: 300 },
    ],
  },
  {
    id: 2,
    name: "South Spice",
    categories: [5, 9],
    image: "/south.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Dosa", price: 120 },
      { id: 2, name: "Uttapam", price: 130 },
      { id: 3, name: "Sambar Rice", price: 100 },
      { id: 4, name: "Coconut Chutney", price: 30 },
    ],
  },
  {
    id: 3,
    name: "Sweet World",
    categories: [3, 6, 13],
    image: "/dessert.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Gulab Jamun", price: 80 },
      { id: 2, name: "Rasgulla", price: 90 },
      { id: 3, name: "Jalebi", price: 70 },
      { id: 4, name: "Kheer", price: 100 },
    ],
  },
  {
    id: 4,
    name: "Tandoori King",
    categories: [1, 7],
    image: "/tandoori.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Tandoori Chicken", price: 350 },
      { id: 2, name: "Tandoori Paneer", price: 300 },
      { id: 3, name: "Tandoori Fish", price: 400 },
      { id: 4, name: "Tandoori Naan", price: 50 },
    ],
  },
  {
    id: 5,
    name: "Curry Master",
    categories: [4, 8],
    image: "/curry.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Butter Chicken Curry", price: 320 },
      { id: 2, name: "Paneer Tikka Masala", price: 280 },
      { id: 3, name: "Chole Masala", price: 180 },
      { id: 4, name: "Rice Bowl", price: 80 },
    ],
  },
  {
    id: 6,
    name: "Chai Corner",
    categories: [12, 14],
    image: "/chai.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Masala Chai", price: 30 },
      { id: 2, name: "Ginger Chai", price: 35 },
      { id: 3, name: "Adrak Chai", price: 40 },
      { id: 4, name: "Chai Biscuits Pack", price: 50 },
    ],
  },
  {
    id: 7,
    name: "Bengal Kitchen",
    categories: [2, 4],
    image: "/bengal.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Luchi Alur Tarkari", price: 150 },
      { id: 2, name: "Machher Jhol", price: 280 },
      { id: 3, name: "Mishti Doi", price: 70 },
      { id: 4, name: "Sandesh", price: 60 },
    ],
  },
  {
    id: 8,
    name: "Southeast Flavors",
    categories: [5, 9],
    image: "/seasia.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Pad Thai", price: 220 },
      { id: 2, name: "Vietnam Pho", price: 240 },
      { id: 3, name: "Tom Yum Soup", price: 200 },
      { id: 4, name: "Spring Rolls", price: 150 },
    ],
  },
  {
    id: 9,
    name: "Tokyo Express",
    categories: [5, 9],
    image: "/tokyo.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Sushi Roll", price: 350 },
      { id: 2, name: "Ramen Noodles", price: 280 },
      { id: 3, name: "Tempura Plate", price: 320 },
      { id: 4, name: "Gyoza", price: 180 },
    ],
  },
  {
    id: 10,
    name: "Shanghai Wok",
    categories: [4, 5],
    image: "/shanghai.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Fried Rice", price: 180 },
      { id: 2, name: "Chow Mein", price: 200 },
      { id: 3, name: "Manchurian Balls", price: 220 },
      { id: 4, name: "Kung Pao Chicken", price: 250 },
    ],
  },
  {
    id: 11,
    name: "European Bistro",
    categories: [1, 8],
    image: "/european.jpg",
    type: "both",
    rating: 4.6,
    menu: [
      { id: 1, name: "Pasta Carbonara", price: 320 },
      { id: 2, name: "Grilled Steak", price: 450 },
      { id: 3, name: "Caesar Salad", price: 200 },
      { id: 4, name: "Bruschetta", price: 150 },
    ],
  },
  {
    id: 12,
    name: "Quick Bites",
    categories: [10, 11],
    image: "/fastfood.jpg",
    type: "both",
    rating: 4.0,
    menu: [
      { id: 1, name: "Burger Combo", price: 180 },
      { id: 2, name: "Fried Chicken", price: 160 },
      { id: 3, name: "Pizza Slice", price: 120 },
      { id: 4, name: "French Fries", price: 80 },
    ],
  },
  {
    id: 13,
    name: "Kebab Palace",
    categories: [1, 7],
    image: "/kebab.jpg",
    type: "non-veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Chicken Seekh Kebab", price: 280 },
      { id: 2, name: "Lamb Kebab", price: 350 },
      { id: 3, name: "Paneer Kebab", price: 240 },
      { id: 4, name: "Kebab Roll", price: 180 },
    ],
  },
  {
    id: 14,
    name: "Noodle Express",
    categories: [5, 9],
    image: "/noodle.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Hakka Noodles", price: 160 },
      { id: 2, name: "Schezwan Noodles", price: 180 },
      { id: 3, name: "Plain Noodles", price: 120 },
      { id: 4, name: "Mixed Veg Noodles", price: 140 },
    ],
  },
  {
    id: 15,
    name: "Pizza Hub",
    categories: [10, 11],
    image: "/pizza.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Margherita Pizza", price: 280 },
      { id: 2, name: "Pepperoni Pizza", price: 320 },
      { id: 3, name: "Veggie Pizza", price: 250 },
      { id: 4, name: "Cheese Crust", price: 300 },
    ],
  },
  {
    id: 16,
    name: "Samosa Stall",
    categories: [10, 11],
    image: "/samosa.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Aloo Samosa", price: 40 },
      { id: 2, name: "Paneer Samosa", price: 60 },
      { id: 3, name: "Meat Samosa", price: 80 },
      { id: 4, name: "Samosa Combo", price: 120 },
    ],
  },
  {
    id: 17,
    name: "Modern Cafe",
    categories: [12, 14],
    image: "/cafe.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Espresso", price: 80 },
      { id: 2, name: "Cappuccino", price: 120 },
      { id: 3, name: "Latte", price: 130 },
      { id: 4, name: "Iced Coffee", price: 100 },
    ],
  },
  {
    id: 18,
    name: "Rajasthani Kitchen",
    categories: [2, 4],
    image: "/rajasthan.jpg",
    type: "veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Dal Baati Churma", price: 200 },
      { id: 2, name: "Gatte Ki Sabzi", price: 180 },
      { id: 3, name: "Bajra Roti", price: 60 },
      { id: 4, name: "Ker Sangri", price: 140 },
    ],
  },
  {
    id: 19,
    name: "Momos House",
    categories: [5, 9],
    image: "/momos.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Chicken Momos", price: 150 },
      { id: 2, name: "Veg Momos", price: 120 },
      { id: 3, name: "Paneer Momos", price: 140 },
      { id: 4, name: "Momo Soup", price: 180 },
    ],
  },
  {
    id: 20,
    name: "Health Bowl",
    categories: [3, 6],
    image: "/health.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Buddha Bowl", price: 280 },
      { id: 2, name: "Quinoa Salad", price: 250 },
      { id: 3, name: "Green Smoothie", price: 150 },
      { id: 4, name: "Protein Shake", price: 180 },
    ],
  },
  {
    id: 21,
    name: "Chole Bhature",
    categories: [2, 4],
    image: "/chole.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Chole Bhature", price: 150 },
      { id: 2, name: "Kulche with Chole", price: 140 },
      { id: 3, name: "Puri with Chole", price: 120 },
      { id: 4, name: "Bhature with Butter", price: 180 },
    ],
  },
  {
    id: 22,
    name: "Waffle Corner",
    categories: [3, 6, 13],
    image: "/waffle.jpg",
    type: "veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Chocolate Waffle", price: 200 },
      { id: 2, name: "Strawberry Waffle", price: 220 },
      { id: 3, name: "Nutella Waffle", price: 240 },
      { id: 4, name: "Plain Waffle", price: 150 },
    ],
  },
  {
    id: 23,
    name: "Grilled Paradise",
    categories: [1, 7],
    image: "/grilled.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Grilled Chicken Breast", price: 380 },
      { id: 2, name: "Grilled Fish Fillet", price: 420 },
      { id: 3, name: "Grilled Vegetables", price: 200 },
      { id: 4, name: "Grilled Paneer", price: 280 },
    ],
  },
  {
    id: 24,
    name: "Idli Sambar",
    categories: [5, 9],
    image: "/idli.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Idli with Sambar", price: 80 },
      { id: 2, name: "Idli with Chutney", price: 70 },
      { id: 3, name: "Gundam Idli", price: 90 },
      { id: 4, name: "Rice Idli", price: 100 },
    ],
  },
  {
    id: 25,
    name: "Fruit Shake Parlor",
    categories: [12, 14],
    image: "/fruitshake.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Mango Shake", price: 120 },
      { id: 2, name: "Banana Shake", price: 100 },
      { id: 3, name: "Strawberry Shake", price: 130 },
      { id: 4, name: "Mixed Fruit Shake", price: 140 },
    ],
  },
  {
    id: 26,
    name: "Korean Grill",
    categories: [5, 9],
    image: "/korean.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Bulgogi", price: 350 },
      { id: 2, name: "Bibimbap", price: 320 },
      { id: 3, name: "Korean Fried Chicken", price: 380 },
      { id: 4, name: "Kimchi Roll", price: 200 },
    ],
  },
  {
    id: 27,
    name: "Panipuri Point",
    categories: [10, 11],
    image: "/panipuri.jpg",
    type: "veg",
    rating: 4.0,
    menu: [
      { id: 1, name: "Panipuri", price: 50 },
      { id: 2, name: "Gol Gappa", price: 60 },
      { id: 3, name: "Bhel Puri", price: 80 },
      { id: 4, name: "Sev Puri", price: 70 },
    ],
  },
  {
    id: 28,
    name: "Thai Cuisine",
    categories: [5, 9],
    image: "/thai.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Green Curry", price: 280 },
      { id: 2, name: "Pad See Ew", price: 260 },
      { id: 3, name: "Massaman Curry", price: 300 },
      { id: 4, name: "Basil Chicken", price: 290 },
    ],
  },
  {
    id: 29,
    name: "Lebanese House",
    categories: [1, 8],
    image: "/lebanese.jpg",
    type: "both",
    rating: 4.3,
    menu: [
      { id: 1, name: "Falafel Wrap", price: 180 },
      { id: 2, name: "Shawarma", price: 220 },
      { id: 3, name: "Hummus Plate", price: 150 },
      { id: 4, name: "Tabbouleh Salad", price: 160 },
    ],
  },
  {
    id: 30,
    name: "Dhaba Style",
    categories: [2, 4],
    image: "/dhaba.jpg",
    type: "both",
    rating: 4.2,
    menu: [
      { id: 1, name: "Sarson Ka Saag", price: 220 },
      { id: 2, name: "Makki Ki Roti", price: 50 },
      { id: 3, name: "Dal Makhani", price: 240 },
      { id: 4, name: "Paneer Butter Masala", price: 280 },
    ],
  },
  {
    id: 31,
    name: "Sandwich Hub",
    categories: [10, 11],
    image: "/sandwich.jpg",
    type: "both",
    rating: 4.1,
    menu: [
      { id: 1, name: "Veggie Sandwich", price: 120 },
      { id: 2, name: "Chicken Sandwich", price: 160 },
      { id: 3, name: "Paneer Sandwich", price: 140 },
      { id: 4, name: "Club Sandwich", price: 200 },
    ],
  },
  {
    id: 32,
    name: "Ice Cream Paradise",
    categories: [3, 6, 13],
    image: "/icecream.jpg",
    type: "veg",
    rating: 4.6,
    menu: [
      { id: 1, name: "Vanilla Scoop", price: 100 },
      { id: 2, name: "Chocolate Scoop", price: 100 },
      { id: 3, name: "Strawberry Scoop", price: 100 },
      { id: 4, name: "Cookie Dough", price: 120 },
    ],
  },
  {
    id: 33,
    name: "Mexican Fiesta",
    categories: [1, 8],
    image: "/mexican.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Tacos", price: 200 },
      { id: 2, name: "Burrito", price: 240 },
      { id: 3, name: "Enchiladas", price: 260 },
      { id: 4, name: "Guacamole Dip", price: 150 },
    ],
  },
  {
    id: 34,
    name: "Dosa King",
    categories: [5, 9],
    image: "/dosakking.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Masala Dosa", price: 130 },
      { id: 2, name: "Paneerdosa", price: 150 },
      { id: 3, name: "Onion Dosa", price: 120 },
      { id: 4, name: "Ghee Roast Dosa", price: 140 },
    ],
  },
  {
    id: 35,
    name: "Pasta Paradise",
    categories: [1, 8],
    image: "/pasta.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Penne Arrabbiata", price: 280 },
      { id: 2, name: "Fettuccine Alfredo", price: 300 },
      { id: 3, name: "Spaghetti Bolognese", price: 290 },
      { id: 4, name: "Lasagna", price: 320 },
    ],
  },
  {
    id: 36,
    name: "Vada Pav Corner",
    categories: [10, 11],
    image: "/vadapav.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Vada Pav", price: 50 },
      { id: 2, name: "Batata Vada", price: 60 },
      { id: 3, name: "Misal Pav", price: 80 },
      { id: 4, name: "Combo Pack", price: 130 },
    ],
  },
  {
    id: 37,
    name: "Juice Bar",
    categories: [12, 14],
    image: "/juicebar.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Orange Juice", price: 80 },
      { id: 2, name: "Apple Juice", price: 90 },
      { id: 3, name: "Carrot Juice", price: 70 },
      { id: 4, name: "Mixed Citrus", price: 100 },
    ],
  },
  {
    id: 38,
    name: "Afghan Breads",
    categories: [1, 7],
    image: "/afghan.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Qabuli Pulao", price: 280 },
      { id: 2, name: "Chapli Kebab", price: 250 },
      { id: 3, name: "Naan", price: 60 },
      { id: 4, name: "Kofta", price: 220 },
    ],
  },
  {
    id: 39,
    name: "Biryani Express",
    categories: [2, 4],
    image: "/biryaniexpress.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Chicken Biryani", price: 260 },
      { id: 2, name: "Mutton Biryani", price: 320 },
      { id: 3, name: "Veg Biryani", price: 200 },
      { id: 4, name: "Fish Biryani", price: 380 },
    ],
  },
  {
    id: 40,
    name: "Crepe Cafe",
    categories: [3, 6],
    image: "/crepe.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Chocolate Crepe", price: 180 },
      { id: 2, name: "Strawberry Crepe", price: 200 },
      { id: 3, name: "Nutella Banana", price: 220 },
      { id: 4, name: "Vanilla Crepe", price: 160 },
    ],
  },
  {
    id: 41,
    name: "Grilled Cheese",
    categories: [10, 11],
    image: "/grilledcheese.jpg",
    type: "veg",
    rating: 4.1,
    menu: [
      { id: 1, name: "Classic Grilled Cheese", price: 140 },
      { id: 2, name: "Bacon Grilled Cheese", price: 180 },
      { id: 3, name: "Tomato Grilled Cheese", price: 160 },
      { id: 4, name: "Veggie Grilled Cheese", price: 150 },
    ],
  },
  {
    id: 42,
    name: "Vietnamese Pho",
    categories: [5, 9],
    image: "/phocafe.jpg",
    type: "both",
    rating: 4.4,
    menu: [
      { id: 1, name: "Beef Pho", price: 240 },
      { id: 2, name: "Chicken Pho", price: 220 },
      { id: 3, name: "Vegetable Pho", price: 180 },
      { id: 4, name: "Seafood Pho", price: 300 },
    ],
  },
  {
    id: 43,
    name: "Soya Chaap House",
    categories: [2, 4],
    image: "/soyachaap.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Tandoori Soya Chaap", price: 220 },
      { id: 2, name: "Gravy Soya Chaap", price: 240 },
      { id: 3, name: "Smoked Soya Chaap", price: 260 },
      { id: 4, name: "Soya Chaap Roll", price: 180 },
    ],
  },
  {
    id: 44,
    name: "Donut Shop",
    categories: [3, 6, 13],
    image: "/donut.jpg",
    type: "veg",
    rating: 4.5,
    menu: [
      { id: 1, name: "Glazed Donut", price: 80 },
      { id: 2, name: "Chocolate Donut", price: 100 },
      { id: 3, name: "Sprinkle Donut", price: 120 },
      { id: 4, name: "Donut Box", price: 300 },
    ],
  },
  {
    id: 45,
    name: "Meatball Joint",
    categories: [1, 8],
    image: "/meatball.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Swedish Meatballs", price: 280 },
      { id: 2, name: "Italian Meatballs", price: 290 },
      { id: 3, name: "Asian Meatballs", price: 260 },
      { id: 4, name: "Meatball Sandwich", price: 220 },
    ],
  },
  {
    id: 46,
    name: "Bhelpuri Stall",
    categories: [10, 11],
    image: "/bhelpuri.jpg",
    type: "veg",
    rating: 4.0,
    menu: [
      { id: 1, name: "Bhel Puri", price: 80 },
      { id: 2, name: "Raj Kachori", price: 90 },
      { id: 3, name: "Chaat Papdi", price: 85 },
      { id: 4, name: "Mix Chaat", price: 120 },
    ],
  },
  {
    id: 47,
    name: "Bubble Tea House",
    categories: [12, 14],
    image: "/bubbletea.jpg",
    type: "veg",
    rating: 4.3,
    menu: [
      { id: 1, name: "Taro Bubble Tea", price: 150 },
      { id: 2, name: "Brown Sugar Boba", price: 160 },
      { id: 3, name: "Matcha Bubble Tea", price: 170 },
      { id: 4, name: "Strawberry Boba", price: 150 },
    ],
  },
  {
    id: 48,
    name: "Fish & Chips Shop",
    categories: [1, 8],
    image: "/fishchips.jpg",
    type: "non-veg",
    rating: 4.4,
    menu: [
      { id: 1, name: "Battered Fish", price: 320 },
      { id: 2, name: "Crispy Fish", price: 300 },
      { id: 3, name: "Fish Fillet", price: 280 },
      { id: 4, name: "Fish & Chips Combo", price: 380 },
    ],
  },
  {
    id: 49,
    name: "Falafel Street",
    categories: [10, 11],
    image: "/falafel.jpg",
    type: "veg",
    rating: 4.2,
    menu: [
      { id: 1, name: "Falafel Plate", price: 160 },
      { id: 2, name: "Falafel Wrap", price: 180 },
      { id: 3, name: "Falafel Salad", price: 200 },
      { id: 4, name: "Spicy Falafel", price: 180 },
    ],
  },
  {
    id: 50,
    name: "Asian Fusion",
    categories: [4, 5],
    image: "/fusion.jpg",
    type: "both",
    rating: 4.5,
    menu: [
      { id: 1, name: "Fusion Bowl", price: 300 },
      { id: 2, name: "Asian Tacos", price: 280 },
      { id: 3, name: "Fusion Noodles", price: 260 },
      { id: 4, name: "Fusion Rice", price: 240 },
    ],
  },
];
